# Generated by Django 4.2.4 on 2023-10-17 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frenchise', '0013_frenchise_employee_register_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefrenchise',
            name='partner_at',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
