# Generated by Django 4.2.4 on 2023-10-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companystaff', '0002_insurance_created_insurance_status_loan_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='created',
            new_name='creation',
        ),
    ]
