# Generated by Django 4.2.4 on 2023-10-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companystaff', '0003_rename_created_loan_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='creation',
            field=models.DateField(max_length=8),
        ),
    ]
